In [6]:
import pandas as pd
import numpy as np
data = pd.read_csv('basic.csv')

In [7]:

from sklearn import preprocessing

x = data.values 
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
data = pd.DataFrame(x_scaled)

In [8]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,0.0,0.601328,0.230527,0.446438,0.072287,0.608142,0.172271,0.575969,0.277145,0.457407,...,0.382956,0.034629,0.538622,0.070778,0.517090,0.015764,0.563737,0.054437,0.792123,0.017678
1,0.0,0.617582,0.299683,0.511990,0.059719,0.612699,0.229410,0.694705,0.179654,0.534436,...,0.381433,0.012721,0.519676,0.074893,0.520590,0.019714,0.567490,0.056816,0.792042,0.013031
2,0.0,0.596793,0.387734,0.514166,0.042276,0.598475,0.314017,0.800411,0.091933,0.508766,...,0.382030,0.091142,0.519515,0.069440,0.527845,0.070755,0.569143,0.057455,0.792000,0.061138
3,0.0,0.594458,0.308676,0.506317,0.049097,0.606255,0.232751,0.705195,0.167194,0.389839,...,0.381907,0.041020,0.551345,0.100292,0.520624,0.044749,0.580961,0.072366,0.791668,0.018604
4,0.0,0.608700,0.340277,0.516487,0.042840,0.619963,0.267143,0.755350,0.129082,0.547522,...,0.382238,0.091701,0.494061,0.083978,0.519798,0.044339,0.566042,0.067444,0.792059,0.030984

In [9]:
size = data.shape[0]
idx = np.arange(size)
np.random.shuffle(idx)
split = int(0.7 * size)
train_idx, test_idx = idx[:split], idx[split:]
data.iloc[train_idx].to_csv("train.csv", index=False)
data.iloc[test_idx].to_csv("test.csv", index=False)